### PR TITLE
fix inbound internet connections counts

### LINKED ISSUE #1867: inbound internet connection counts are too fine-grained
screenshot from 2016-09-15 11-21-43
The two connections are from the same address, so we should only have one row, with a count of 2.

This happens because the counter key for internet connections contains the endpoint id, which includes the port. That is fine for outbound internet connections, since there we do care about the port (though it's redundant, since the port is also part of the key directly). But not for inbound internet connections.

### PR DESCRIPTION
**Pull request by rade**
Fixes #1867.

### CODE REVIEW

File: render/detailed/node_test.go [hunk 1]
```diff
@@ -149,7 +149,7 @@ func TestMakeDetailedHostNode(t *testing.T) {
 				Columns:    detailed.NormalColumns,
 				Connections: []detailed.Connection{
 					{
-						ID:       fmt.Sprintf("%s:%s-%s:%s-%d", fixture.ServerHostNodeID, "", fixture.ClientHostNodeID, "", 80),
+						ID:       fmt.Sprintf("%s-%s-%d", fixture.ServerHostNodeID, "", 80),
```
Comment (rade) [inline render/detailed/node_test.go]: I did consider that, but it's not really much of an abstraction - the *contents* of the ID are far more likely to change than the formatting alone, so any change would entail a change in the function and the call sites. I suppose the compiler gives you some help in complaining about mismatches, so perhaps it's worth for that. Will give it a go.

Comment (rade) [inline render/detailed/node_test.go]: done. PTAL
