### PR TITLE
fix internet connection counts

### LINKED ISSUE #1495: Incorrect number of connections shown on internet nodes
The +17 is wrong:

screen shot 2016-05-12 at 16 55 36

### PR DESCRIPTION
**Pull request by rade**
Fixes #1495.

### CODE REVIEW

**Comment by rade** [comment]
@paulbellamy this does perhaps deserve a unit test, but I am not familiar with all the data structures involved, so this is a bit daunting. If you do think this should have a test, would you mind helping me write one?

File: render/detailed/connections.go [hunk 1]
```diff
@@ -115,7 +110,7 @@ func incomingConnectionsSummary(topologyID string, r report.Report, n report.Nod
 		TopologyID:  topologyID,
 		Label:       "Inbound",
 		Columns:     columnHeaders,
-		Connections: connectionRows(r, counts, isInternetNode(n)),
+		Connections: connectionRows(r, ns, counts, isInternetNode(n)),
```
Comment (rade) [inline render/detailed/connections.go]: I am assuming that `ns` contains `n` as well as all the local endpoints. Is that safe?

**Comment by paulbellamy** [comment]
> this does perhaps deserve a unit test

yes, please!

File: render/detailed/connections.go (hunk 1 above)
Comment (paulbellamy) [inline render/detailed/connections.go]: Safe enough, as they have all been pulled out of the rendered nodes at some point. It would be nice if that had better locality.

Comment (rade) [inline render/detailed/connections.go]: The former yes. The latter, no. As a result we fail to look up the reverse DNS resolution in `connectionRows()`. Grrr.

Comment (rade) [inline render/detailed/connections.go]: Fixed.

**Comment by davkal** [comment]
I'm not getting the following in the details panel for the Internet:
```
Inbound Remote Port Count
X    IP1       PortA    2
Y    IP2       PortB   2
Y    IP2       PortB   2
Y    IP2       PortB   2
X    IP3       PortA    2
```
and with +51 (which works as expected.

Having multiple rows with all values identical looks confusing. I'm guessing those 3 Y rows, are 3 different containers with the same name.

UX remedies:

* aggregate counts to one row if all other fields are the same
* add a column for a field that varies across the rows
* add a hover over the name

**Comment by rade** [comment]
> UX remedies:
>
>    aggregate counts to one row if all other fields are the same

That would break the navigation, i.e. I need to be able to navigate to the 3 individual containers, so need 3 click-able things.

>    add a column for a field that varies across the rows

That would be best, but we are really short on horizontal space here.

>    add a hover over the name

That might be the only choice left :(

Please file an issue.

**Comment by davkal** [comment]
Filed #1844 for UI issues.

**Comment by paulbellamy** [comment]
LGTM

**Comment by rade** [comment]
I've given up on constructing a test for this. It's just too hard, for me at least, not being familiar with the entire report data structure, and the intricacies of `fixture.Report`. I have filed #1845.
