### PR TITLE
Fix weave tagger crash

### LINKED ISSUE #955: Crash on weave tagger
```
panic: runtime error: slice bounds out of range

goroutine 42 [running]:
github.com/weaveworks/scope/probe/overlay.(*Weave).Tag(0xc82012eb80, 0xc8213d5380, 0xc8213d53b0, 0xc8213d53e0, 0xc8213d5410, 0xc8213d5440, 0xc820fc6510, 0xc820fc6540, 0xc820fd66f0, 0xc820fd6840, ...)
        /go/src/github.com/weaveworks/scope/probe/overlay/weave.go:139 +0x85a
github.com/weaveworks/scope/probe.(*Probe).tag(0xc8200a59e0, 0xc8213d5380, 0xc8213d53b0, 0xc8213d53e0, 0xc8213d5410, 0xc8213d5440, 0xc820fc6510, 0xc820fc6540, 0xc820fd66f0, 0xc820fd6840, ...)
        /go/src/github.com/weaveworks/scope/probe/probe.go:160 +0x200
github.com/weaveworks/scope/probe.(*Probe).spyLoop(0xc8200a59e0)
        /go/src/github.com/weaveworks/scope/probe/probe.go:111 +0x184
created by github.com/weaveworks/scope/probe.(*Probe).Start
        /go/src/github.com/weaveworks/scope/probe/probe.go:85 +0x58
```

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #955

### CODE REVIEW

**Comment by 2opremio** [comment]
@paulbellamy @tomwilkie PTAL

File: probe/overlay/weave.go [hunk 1]
```diff
@@ -134,9 +134,15 @@ func (w *Weave) Tag(r report.Report) (report.Report, error) {
 	}
 
 	// Put information from weave ps on the container nodes
+	const maxPrefixSize = 12
 	for id, node := range r.Container.Nodes {
-		prefix, _ := node.Latest.Lookup(docker.ContainerID)
-		prefix = prefix[:12]
+		prefix, ok := node.Latest.Lookup(docker.ContainerID)
+		if !ok {
```
Comment (2opremio) [inline probe/overlay/weave.go]: In my repro (a Kubernetes cluster) this was failing because the lookup failed. Is this an invariant? 

I am asking in case this was just the symptom of something else being broken,

Comment (paulbellamy) [inline probe/overlay/weave.go]: How would you ever get a container with no id?

Comment (2opremio) [inline probe/overlay/weave.go]: Since you are asking, I guess it's an invariant. I don't know, I guess I can try to print the node.

Comment (2opremio) [inline probe/overlay/weave.go]: OK, I got an example:

```
Container node without a containerID:
 (report.Node) {
 ID: (string) (len=76) "da0529205329de047c90c481cee0ee7b9d7142344a20dc5a095c3f8a03298dde;<container>",
 Topology: (string) (len=9) "container",
 Counters: (report.Counters) {}
,
 Sets: (report.Sets) {}
,
 Adjacency: (report.IDList) <nil>,
 Edges: (report.EdgeMetadatas) {}
,
 Controls: (report.NodeControls) {
  Timestamp: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
  Controls: (report.StringSet) <nil>
 },
 Latest: (report.LatestMap) {host_node_id: "ip-172-20-0-62;<host>" (2016-02-18 14:21:44.322386755 +0000 UTC),
kubernetes_namespace: "default" (2016-02-18 14:21:44.255092505 +0000 UTC),
kubernetes_pod_id: "default/weave-scope-probe-0gkyr" (2016-02-18 14:21:44.255092505 +0000 UTC),
probe_id: "498878ebc915ca60" (2016-02-18 14:21:44.322386755 +0000 UTC),
}
,
 Metrics: (report.Metrics) {
 },
 Parents: (report.Sets) {host: [ip-172-20-0-62;<host>], pod: [default;weave-scope-probe-0gkyr], }

}
2016/02/18 14:21:44 Container node without a containerID:
 (report.Node) {
 ID: (string) (len=76) "7e8711351e64ac4bdd3b4c28ed1f00381a82733a83731cd538f36e216b2be00b;<container>",
 Topology: (string) (len=9) "container",
 Counters: (report.Counters) {}
,
 Sets: (report.Sets) {}
,
 Adjacency: (report.IDList) <nil>,
 Edges: (report.EdgeMetadatas) {}
,
 Controls: (report.NodeControls) {
  Timestamp: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
  Controls: (report.StringSet) <nil>
 },
 Latest: (report.LatestMap) {host_node_id: "ip-172-20-0-62;<host>" (2016-02-18 14:21:44.322457104 +0000 UTC),
kubernetes_namespace: "kube-system" (2016-02-18 14:21:44.255717904 +0000 UTC),
kubernetes_pod_id: "kube-system/fluentd-elasticsearch-ip-172-20-0-91.ec2.internal" (2016-02-18 14:21:44.255717904 +0000 UTC),
probe_id: "498878ebc915ca60" (2016-02-18 14:21:44.322457104 +0000 UTC),
}
,
 Metrics: (report.Metrics) {
 },
 Parents: (report.Sets) {host: [ip-172-20-0-62;<host>], pod: [kube-system;fluentd-elasticsearch-ip-172-20-0-91.ec2.internal], }

}
```

Comment (2opremio) [inline probe/overlay/weave.go]: Here's another one

```
Container node without a containerID:
 (report.Node) {
 ID: (string) (len=76) "a6950b6a58fad722167f69c6444d2e4a88453eebc9aec24c32c4dec2664d890e;<container>",
 Topology: (string) (len=9) "container",
 Counters: (report.Counters) {}
,
 Sets: (report.Sets) {}
,
 Adjacency: (report.IDList) <nil>,
 Edges: (report.EdgeMetadatas) {}
,
 Controls: (report.NodeControls) {
  Timestamp: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
  Controls: (report.StringSet) <nil>
 },
 Latest: (report.LatestMap) {host_node_id: "ip-172-20-0-62;<host>" (2016-02-18 14:21:44.322339369 +0000 UTC),
kubernetes_namespace: "default" (2016-02-18 14:21:44.255643119 +0000 UTC),
kubernetes_pod_id: "default/scope-app-157-at2bw" (2016-02-18 14:21:44.255643119 +0000 UTC),
probe_id: "498878ebc915ca60" (2016-02-18 14:21:44.322339369 +0000 UTC),
}
,
 Metrics: (report.Metrics) {
 },
 Parents: (report.Sets) {host: [ip-172-20-0-62;<host>], pod: [default;scope-app-157-at2bw], }

}
```

Comment (2opremio) [inline probe/overlay/weave.go]: I think that the kubernetes reporter is *breaking* the lookup invariant. As soon as I stop providing `--probe.kubernetes=true` to the probes I don't get any lookup failures.

**Comment by tomwilkie** [comment]
All container nodes should have a docker.ContainerID, but this should be more robust.  Please also fix the kubernetes reporter in this PR.

**Comment by 2opremio** [comment]
@tomwilkie I just did :)

**Comment by tomwilkie** [comment]
On minor nit, otherwise LGTM.

We should have a integration test for scope on k8s, as this isn't something we seem to test with in the normal course of development.
