### PR TITLE
Fix details panel links

### LINKED ISSUE #2263: Details panel links not working
Error in the console on link click:

Uncaught TypeError: this.props.dispatch is not a function

### PR DESCRIPTION
**Pull request by fbarl**
Fixes #2263 that was caused by accidentally disconnecting `NodeDetailsControlButton`, `NodeDetailsRelativesLink` and `NodeDetailsTableNodeLink` components from Redux in the PR #2221 (commit https://github.com/weaveworks/scope/pull/2221/commits/e5c655aa880e9a7931c359ae275d3d732afc6033).

### CODE REVIEW

File: client/app/scripts/components/node-details/node-details-relatives-link.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 import React from 'react';
+import { connect } from 'react-redux';
 
 import { clickRelative } from '../../actions/app-actions';
 import MatchedText from '../matched-text';
 
-export default class NodeDetailsRelativesLink extends React.PureComponent {
+class NodeDetailsRelativesLink extends React.Component {
```
Comment (jpellizzari) [inline client/app/scripts/components/node-details/node-details-relatives-link.js]: Why the change from PureComponent to regular?

Comment (fbarl) [inline client/app/scripts/components/node-details/node-details-relatives-link.js]: Because, as I understand it, Redux already does the `props` comparison the same way `PureComponent` does. In fact, `PureComponent` is a relatively new concept in Redux that we were simulating before by an *empty* Redux connect. :)

Comment (jpellizzari) [inline client/app/scripts/components/node-details/node-details-relatives-link.js]: Nvm, I see your comment.

**Comment by jpellizzari** [comment]
LGTM. Merging.
