### PR TITLE
Fixes metrics-on-canvas updating.

### LINKED ISSUE #1829: Metrics on canvas get stuck
They don't seem to refresh properly when hovering on them. Clicking on the node to show the details panel seems to _refresh_ them.

I would expect the metrics to refresh while hovering and between hovers.

### PR DESCRIPTION
**Pull request by foot**
- We were being a bit overzealous w/ our layout caching.

Fixes #1829

### CODE REVIEW

**Comment by foot** [comment]
We're back to over-calculating layouts, this doesn't feel too expensive when testing but maybe I'm missing something.

A nicer caching mechanism would be to introduce something like re-select and pull out the graph layout dependencies a bit more.

**Comment by 2opremio** [comment]
@foot Would you mind rebasing? The build was broken and we just fixed it in master.

File: client/app/scripts/charts/nodes-chart.js [hunk 1]
```diff
@@ -82,8 +81,7 @@ class NodesChart extends React.Component {
     state.height = nextProps.forceRelayout ? nextProps.height : (state.height || nextProps.height);
     state.width = nextProps.forceRelayout ? nextProps.width : (state.width || nextProps.width);
 
-    // _.assign(state, this.updateGraphState(nextProps, state));
-    if (nextProps.forceRelayout || !isSameTopology(nextProps.nodes, this.props.nodes)) {
+    if (nextProps.forceRelayout || nextProps.nodes !== this.props.nodes) {
```
Comment (davkal) [inline client/app/scripts/charts/nodes-chart.js]: Two things are getting mixed up here. Generally, in this class `props.nodes` have to become `state.nodes`, otherwise the changes wont be rendered.

This section makes sure not to run the layout engine code if the topo has not changed, it does create `state.nodes` along the way. (I guess this is bad design.)

What you need is `props.nodes`' properties being merged into `state.nodes` if `props.nodes` and `nextProps.nodes` are not the same. This should be a separate step.

**Comment by foot** [comment]
@davkal PT another quick L, we are 1.5fps slower than master (18.5 vs 20) using reselect and I'm not sure exactly whyyy, similar numbers from react perf re: number of render() calls etc, (ofc master is not rendering MOC correctly).

I'd merge this and then look into using reselect in other parts of the system to hopefully improve perf WDYT?

**Comment by rade** [comment]
@foot what is left to do here? @davkal says you asked him "to hold off" on this PR.

**Comment by foot** [comment]
@davkal fixed hanging edges, PTAL!

File: client/app/scripts/selectors/chartSelectors.js [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+//   - v1 = getAdjacentNodes(a)
+//   - v2 = getAdjacentNodes(a)
+//   - v1 !== v2
+//   - is(v1, v2) === true
+//
+// - createDeepEqualSelector will wrap those calls with a: is(v1, v2) ? v1 : v2
+//   - Thus you can compare consecutive calls to adjacentNodesSelector(state) with === (which is
+//     what redux is doing with connect()
+//
+// Note: this feels like the wrong way to be using reselect...
```
Comment (davkal) [inline client/app/scripts/selectors/chartSelectors.js]: Yes, you should be able to rewrite `getAdjacentNodes` so it takes `nodes` (filtered) and `origin` as inputs. Then those two become the selectors, and `getAdjacentNodes` will be fully memoizable.

File: client/app/scripts/selectors/chartSelectors.js [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+    (nodes) => nodes.map(n => makeMap({
+      id: n.get('id'),
+      adjacency: n.get('adjacency'),
+    }))
+  ),
+  identity
+);
+
+
+export const dataNodesSelector = createSelector(
```
Comment (davkal) [inline client/app/scripts/selectors/chartSelectors.js]: No potential for deepEqual? This means this selector always returns something new.

File: client/app/scripts/selectors/chartSelectors.js [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+    //
+    if (layoutNodes.size !== dataNodes.size) {
+      log('Obviously mismatched node data', layoutNodes.size, dataNodes.size);
+    }
+    return mergeDeepKeyIntersection(dataNodes, layoutNodes);
+  }
+);
+
+
+export const completeNodesSelector = createDeepEqualSelector(
```
Comment (davkal) [inline client/app/scripts/selectors/chartSelectors.js]: Couldnt you simply make `_completeNodesSelector` a `createDeepEqualSelector` ?

File: client/app/scripts/selectors/chartSelectors.js [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+//
+export const nodeAdjacenciesSelector = createDeepEqualSelector(
+  createSelector(
+    nodesSelector,
+    (nodes) => nodes.map(n => makeMap({
+      id: n.get('id'),
+      adjacency: n.get('adjacency'),
+    }))
+  ),
+  identity
```
Comment (davkal) [inline client/app/scripts/selectors/chartSelectors.js]: This is not needed, is it?

File: client/app/scripts/charts/nodes-chart.js [hunk 6]
```diff
@@ -3,17 +3,17 @@ import d3 from 'd3';
...
+import { nodeAdjacenciesSelector, adjacentNodesSelector } from '../selectors/chartSelectors';
 import { clickBackground } from '../actions/app-actions';
 import { EDGE_ID_SEPARATOR } from '../constants/naming';
 import { MIN_NODE_SIZE, DETAILS_PANEL_WIDTH, MAX_NODE_SIZE } from '../constants/styles';
 import Logo from '../components/logo';
 import { doLayout } from './nodes-layout';
 import NodesChartElements from './nodes-chart-elements';
-import { getActiveTopologyOptions, getAdjacentNodes,
-  isSameTopology } from '../utils/topology-utils';
+import { getActiveTopologyOptions } from '../utils/topology-utils';
```
Comment (davkal) [inline client/app/scripts/charts/nodes-chart.js]: This looks like another selector candidate.

File: client/app/scripts/charts/nodes-chart.js [hunk 7]
```diff
@@ -391,16 +390,19 @@ class NodesChart extends React.Component {
   }
 }
 
+
 function mapStateToProps(state) {
   return {
-    adjacentNodes: getAdjacentNodes(state),
+    nodes: nodeAdjacenciesSelector(state),
```
Comment (davkal) [inline client/app/scripts/charts/nodes-chart.js]: This is selector is not working as hoped. My test topology has regular node delta `update` events, but no adding/removing. Yet it's going into `updateGraphState` which is a little more expensive.
The trouble is that `nodes-chart:componentWillReceiveProps` is firing a lot, so there should be extra care in not doing too much work there.

File: client/app/scripts/charts/nodes-chart.js (hunk 6 above)
Comment (foot) [inline client/app/scripts/charts/nodes-chart.js]: Yep! This first pass I didn't selectorify much stuff, lots of things can be selector'd!

File: client/app/scripts/charts/nodes-chart.js (hunk 7 above)
Comment (foot) [inline client/app/scripts/charts/nodes-chart.js]: Strange! Adjacencies are not changing? (`update`). Will try and create a test case kind of thing...

File: client/app/scripts/selectors/chartSelectors.js (hunk 4 above)
Comment (foot) [inline client/app/scripts/selectors/chartSelectors.js]: Yes, that would have a similar effect.

File: client/app/scripts/selectors/chartSelectors.js (hunk 3 above)
Comment (foot) [inline client/app/scripts/selectors/chartSelectors.js]: Yep, bit of a judgement call here, if nodes has changed something has probably changed in here (metrics). All this talk of expensive deep equality checks has made me a bit cautious about using it everywhere.

File: client/app/scripts/selectors/chartSelectors.js (hunk 5 above)
Comment (foot) [inline client/app/scripts/selectors/chartSelectors.js]: Yep, this weird createDeepEqualSelector+identity wrapper ensures that we get back the previous value they were deep equal, I refactored this (sorry) to make that clearer and will push in a sec.

File: client/app/scripts/selectors/chartSelectors.js [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+);
+
+
+const identity = v => v;
+
+
+const allNodesSelector = state => state.get('nodes');
+
+
+export const nodesSelector = createSelector(
```
Comment (foot) [inline client/app/scripts/selectors/chartSelectors.js]: `createSelector` checks its arguments (state.get('nodes') in this case) not the result. we could wrap it in the createDeepEqualSelector+identity dance to check its result however! good point.

File: client/app/scripts/selectors/chartSelectors.js (hunk 2 above)
Comment (foot) [inline client/app/scripts/selectors/chartSelectors.js]: True!

**Comment by foot** [comment]
I refactored the selectors again (sorry!), to make the intention clearer. That is: (as you say) trying to avoid the calling of `componentWillReceiveProps` and triggering a layout. 

When we hopefully move the layout code into a selector itself we can guard it from being called wastefully by using the traditional immutablejs+reselect pattern suggested in their README.md (a vanilla createDeepEqualSelector).

As our layout code is in a component for now we guard it by being careful that mapStateToProps always returns `===`able values. In the version of the code you reviewed this was awkwardly done w/ an inline `createDeepEqualSelector(anonymousSelector, identity)`, I pulled that out into a documented helper wrapper function called... `returnPreviousRefIfEqual`. It wraps the selectors that feed `nodes-chart` avoiding updating the props if it can.

**Comment by davkal** [comment]
Works well! LGTM
