### PR TITLE
Stop mutating nodes in the rendering pipeline

### LINKED ISSUE #1087: Concurrent map writes panic on go 1.6
```
fatal error: concurrent map writes

goroutine 302 [running]:
runtime.throw(0x182f9a0, 0x15)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8224a9140 sp=0xc8224a9128
runtime.mapassign1(0x15e0900, 0xc8217e1ec0, 0xc8224a92f8, 0xc8224a9788)
	/usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8224a91e8 sp=0xc8224a9140
github.com/weaveworks/scope/render.containerWithImageNameRenderer.Render(0x7ffa1d5f7150, 0xc8203e9740, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, ...)
	/go/src/github.com/weaveworks/scope/render/topologies.go:189 +0x3a8 fp=0xc8224a98f0 sp=0xc8224a91e8
github.com/weaveworks/scope/render.(*containerWithImageNameRenderer).Render(0xc8203dad80, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	<autogenerated>:61 +0xbb fp=0xc8224a99d0 sp=0xc8224a98f0
github.com/weaveworks/scope/render.(*Filter).render(0xc8224aa798, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:78 +0xee fp=0xc8224aa6a0 sp=0xc8224a99d0
github.com/weaveworks/scope/render.Filter.Stats(0x7ffa1d5f7228, 0xc8203dad80, 0x1a18f80, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:117 +0x4c fp=0xc8224aa798 sp=0xc8224aa6a0
github.com/weaveworks/scope/render.(*Filter).Stats(0xc8211185e0, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	<autogenerated>:50 +0xce fp=0xc8224aa880 sp=0xc8224aa798
github.com/weaveworks/scope/render.(*memoise).Stats(0xc821118600, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	<autogenerated>:51 +0x83 fp=0xc8224aa968 sp=0xc8224aa880
github.com/weaveworks/scope/render.Filter.Stats(0x7ffa1d5f7090, 0xc821118600, 0x1a18f70, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:118 +0x98 fp=0xc8224aaa60 sp=0xc8224aa968
github.com/weaveworks/scope/render.(*Filter).Stats(0xc8211186e0, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	<autogenerated>:50 +0xce fp=0xc8224aab48 sp=0xc8224aaa60
github.com/weaveworks/scope/render.(*memoise).Stats(0xc821118720, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	<autogenerated>:51 +0x83 fp=0xc8224aac30 sp=0xc8224aab48
github.com/weaveworks/scope/app.decorateWithStats(0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, 0xc8217666f0, ...)
	/go/src/github.com/weaveworks/scope/app/api_topologies.go:230 +0x1c9 fp=0xc8224ab040 sp=0xc8224aac30
github.com/weaveworks/scope/app.(*registry).renderTopologies.func1(0x175b910, 0xa, 0x0, 0x0, 0x7ffa1d5f7228, 0xc8203dad80, 0x174cb80, 0xa, 0x2, 0xc8203c7b30, ...)
	/go/src/github.com/weaveworks/scope/app/api_topologies.go:207 +0xa8 fp=0xc8224ab1b0 sp=0xc8224ab040
github.com/weaveworks/scope/app.(*registry).walk(0x23f0480, 0xc8224ab598)
	/go/src/github.com/weaveworks/scope/app/api_topologies.go:191 +0x2bc fp=0xc8224ab570 sp=0xc8224ab1b0
github.com/weaveworks/scope/app.(*registry).renderTopologies(0x23f0480, 0xc820c8cf60, 0xc820cf7050, 0xc820cf7080, 0xc821756480, 0xc8217564b0, 0xc8222e4de0, 0xc8222e4e10, 0xc8226d2f30, 0xc8217666c0, ...)
	/go/src/github.com/weaveworks/scope/app/api_topologies.go:213 +0xa7 fp=0xc8224ab5c0 sp=0xc8224ab570
github.com/weaveworks/scope/app.(*registry).makeTopologyList.func1(0x7ffa1d5f9238, 0xc820f36120, 0x7ffa1d5f91c0, 0xc820d9a4c0, 0xc8201501c0)
	/go/src/github.com/weaveworks/scope/app/api_topologies.go:198 +0xb5 fp=0xc8224ab7b8 sp=0xc8224ab5c0
github.com/weaveworks/scope/app.requestContextDecorator.func1(0x7ffa1d5f91c0, 0xc820d9a4c0, 0xc8201501c0)
	/go/src/github.com/weaveworks/scope/app/router.go:37 +0x226 fp=0xc8224ab8a0 sp=0xc8224ab7b8
net/http.HandlerFunc.ServeHTTP(0xc8203ba360, 0x7ffa1d5f91c0, 0xc820d9a4c0, 0xc8201501c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8224ab8c0 sp=0xc8224ab8a0
github.com/weaveworks/scope/vendor/github.com/PuerkitoBio/ghost/handlers.GZIPHandler.func1(0x7ffa1d5f90a8, 0xc821666000, 0xc8201501c0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/PuerkitoBio/ghost/handlers/gzip.go:127 +0x330 fp=0xc8224ab958 sp=0xc8224ab8c0
net/http.HandlerFunc.ServeHTTP(0xc8203ebf80, 0x7ffa1d5f90a8, 0xc821666000, 0xc8201501c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8224ab978 sp=0xc8224ab958
github.com/weaveworks/scope/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203dc500, 0x7ffa1d5f90a8, 0xc821666000, 0xc8201501c0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/mux/mux.go:100 +0x29e fp=0xc8224aba90 sp=0xc8224ab978
github.com/weaveworks/scope/app.TopologyHandler.func1(0x7ffa1d5f90a8, 0xc821666000, 0xc8201501c0)
	/go/src/github.com/weaveworks/scope/app/router.go:113 +0xa7 fp=0xc8224abb20 sp=0xc8224aba90
net/http.HandlerFunc.ServeHTTP(0xc8203d4fa0, 0x7ffa1d5f90a8, 0xc821666000, 0xc8201501c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8224abb40 sp=0xc8224abb20
net/http.serverHandler.ServeHTTP(0xc820153d00, 0x7ffa1d5f90a8, 0xc821666000, 0xc8201501c0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc8224abba0 sp=0xc8224abb40
net/http.(*conn).serve(0xc82006b500)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc8224abf68 sp=0xc8224abba0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8224abf70 sp=0xc8224abf68
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [chan receive, 33 minutes]:
github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common.SignalHandlerLoop(0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common/signals.go:20 +0x2ff
main.appMain()
	/go/src/github.com/weaveworks/scope/prog/app.go:86 +0xa19
main.main()
	/go/src/github.com/weaveworks/scope/prog/main.go:63 +0x2ce

goroutine 17 [syscall, 33 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 18 [syscall, 33 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 22 [chan receive]:
github.com/weaveworks/scope/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x23f0f00)
	/go/src/github.com/weaveworks/scope/vendor/github.com/golang/glog/glog.go:882 +0x67
created by github.com/weaveworks/scope/vendor/github.com/golang/glog.init.1
	/go/src/github.com/weaveworks/scope/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 35 [runnable]:
github.com/weaveworks/scope/render.(*Filter).render(0xc8203d43a0, 0xc8215049c0, 0xc820a2eba0, 0xc820a2ebd0, 0xc8216d6a80, 0xc8216d6ab0, 0xc8224f9cb0, 0xc8224f9ce0, 0xc821dc4c30, 0xc821e83050, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:80 +0x23a
github.com/weaveworks/scope/render.(*Filter).Render(0xc8203d43a0, 0xc8215049c0, 0xc820a2eba0, 0xc820a2ebd0, 0xc8216d6a80, 0xc8216d6ab0, 0xc8224f9cb0, 0xc8224f9ce0, 0xc821dc4c30, 0xc821e83050, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:70 +0x3e
github.com/weaveworks/scope/render.(*memoise).Render(0xc8203d4400, 0xc8215049c0, 0xc820a2eba0, 0xc820a2ebd0, 0xc8216d6a80, 0xc8216d6ab0, 0xc8224f9cb0, 0xc8224f9ce0, 0xc821dc4c30, 0xc821e83050, ...)
	/go/src/github.com/weaveworks/scope/render/memoise.go:35 +0x2c4
github.com/weaveworks/scope/render.(*Filter).render(0xc8203d4420, 0xc8215049c0, 0xc820a2eba0, 0xc820a2ebd0, 0xc8216d6a80, 0xc8216d6ab0, 0xc8224f9cb0, 0xc8224f9ce0, 0xc821dc4c30, 0xc821e83050, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:78 +0xee
github.com/weaveworks/scope/render.(*Filter).Render(0xc8203d4420, 0xc8215049c0, 0xc820a2eba0, 0xc820a2ebd0, 0xc8216d6a80, 0xc8216d6ab0, 0xc8224f9cb0, 0xc8224f9ce0, 0xc821dc4c30, 0xc821e83050, ...)
	/go/src/github.com/weaveworks/scope/render/filters.go:70 +0x3e
github.com/weaveworks/scope/render.(*memoise).Render(0xc8203d4440, 0xc8215049c0, 0xc820a2eba0, 0xc820a2ebd0, 0xc8216d6a80, 0xc8216d6ab0, 0xc8224f9cb0, 0xc8224f9ce0, 0xc821dc4c30, 0xc821e83050, ...)
	/go/src/github.com/weaveworks/scope/render/memoise.go:35 +0x2c4
github.com/weaveworks/scope/app.handleWebsocket(0x7ffa1d5f9238, 0xc8203c6f90, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0, 0x7ffa1d5f76f8, 0xc8203b57c0, 0x7ffa1d5f7090, 0xc8203d4440, 0x12a05f200)
	/go/src/github.com/weaveworks/scope/app/api_topology.go:105 +0x295
github.com/weaveworks/scope/app.handleWs(0x7ffa1d5f9238, 0xc8203c6f90, 0x7ffa1d5f76f8, 0xc8203b57c0, 0x7ffa1d5f7090, 0xc8203d4440, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/go/src/github.com/weaveworks/scope/app/api_topology.go:50 +0x2a3
github.com/weaveworks/scope/app.(*registry).captureRenderer.func1(0x7ffa1d5f9238, 0xc8203c6f90, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/go/src/github.com/weaveworks/scope/app/api_topologies.go:266 +0x1eb
github.com/weaveworks/scope/app.requestContextDecorator.func1(0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/go/src/github.com/weaveworks/scope/app/router.go:37 +0x226
net/http.HandlerFunc.ServeHTTP(0xc8203baa10, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/weaveworks/scope/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203dc500, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
github.com/weaveworks/scope/app.TopologyHandler.func1(0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/go/src/github.com/weaveworks/scope/app/router.go:120 +0x1df
net/http.HandlerFunc.ServeHTTP(0xc8203d4fa0, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820153d00, 0x7ffa1d5f90a8, 0xc8201740d0, 0xc8203681c0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8202ea000)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 51 [select, 33 minutes]:
github.com/weaveworks/scope/vendor/github.com/weaveworks/go-checkpoint.CheckInterval.func1(0x13a52453c000, 0xc820152a80, 0x1a1cfb8, 0xc8202c0720)
	/go/src/github.com/weaveworks/scope/vendor/github.com/weaveworks/go-checkpoint/checkpoint.go:205 +0x131
created by github.com/weaveworks/scope/vendor/github.com/weaveworks/go-checkpoint.CheckInterval
	/go/src/github.com/weaveworks/scope/vendor/github.com/weaveworks/go-checkpoint/checkpoint.go:213 +0xb7

goroutine 52 [select]:
github.com/weaveworks/scope/common/backoff.(*backoff).Start(0xc8203b5780)
	/go/src/github.com/weaveworks/scope/common/backoff/backoff.go:84 +0x3be
created by github.com/weaveworks/scope/app.NewWeavePublisher
	/go/src/github.com/weaveworks/scope/app/weave.go:81 +0x2fe

goroutine 53 [select]:
github.com/weaveworks/scope/app.(*localPipeRouter).gcLoop(0xc8203a0270)
	/go/src/github.com/weaveworks/scope/app/pipe_router.go:142 +0x156
created by github.com/weaveworks/scope/app.NewLocalPipeRouter
	/go/src/github.com/weaveworks/scope/app/pipe_router.go:76 +0x122

goroutine 54 [IO wait]:
net.runtime_pollWait(0x7ffa1d5f88c0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82056dd40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82056dd40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82056dce0, 0x0, 0x7ffa1d5f89b8, 0xc820a72d80)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201201d0, 0x461f20, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8201201d0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc820153d00, 0x7ffa1d5f8980, 0xc8201201d0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc820153d00, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc8203dadb8, 0x5, 0x7ffa1e7d9090, 0xc8203d4fa0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x98
main.appMain.func2(0xc8203dadc0, 0x7ffa1e7d9090, 0xc8203d4fa0)
	/go/src/github.com/weaveworks/scope/prog/app.go:83 +0x124
created by main.appMain
	/go/src/github.com/weaveworks/scope/prog/app.go:84 +0xa04

goroutine 55 [select, 33 minutes, locked to thread]:
runtime.gopark(0x1a1d828, 0xc82001b728, 0x1743930, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82001b728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82001b728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 64 [IO wait]:
net.runtime_pollWait(0x7ffa1d5f8500, 0x72, 0xc8207df000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820596610, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820596610, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205965b0, 0xc8207df000, 0x1000, 0x1000, 0x0, 0x7ffa2001c050, 0xc82000e018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820116028, 0xc8207df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820064420)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820064420, 0xc8202de468, 0x2, 0x8, 0x23f09c0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).readFull(0xc8200c6500, 0xc8202de468, 0x2, 0x8, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:617 +0xa9
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc8200c6500, 0x9, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:641 +0x159
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc8200c6500, 0x1a1d930, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:780 +0x80
github.com/weaveworks/scope/common/xfer.(*pingingWebsocket).ReadJSON(0xc8203e0880, 0x11f4940, 0xc8203e08c0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/common/xfer/websocket.go:146 +0x96
github.com/weaveworks/scope/common/xfer.(*JSONWebsocketCodec).readMessage(0xc8203e08a0, 0x0, 0x0, 0x41de82, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/common/xfer/controls.go:113 +0xf4
github.com/weaveworks/scope/common/xfer.(*JSONWebsocketCodec).ReadResponseHeader(0xc8203e08a0, 0xc8202c9380, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/common/xfer/controls.go:123 +0x3d
net/rpc.(*Client).input(0xc8200644e0)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd7

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7ffa1d5f8380, 0x72, 0xc8205b0000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8205c4920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205c4920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205c48c0, 0xc8205b0000, 0x1000, 0x1000, 0x0, 0x7ffa2001c050, 0xc82000e018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201201e8, 0xc8205b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.(*connReader).Read(0xc8203879a0, 0xc8205b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:526 +0x196
bufio.(*Reader).fill(0xc8202c0fc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202c0fc0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*conn).readRequest(0xc820118d00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:702 +0x2e6
net/http.(*conn).serve(0xc820118d00)
	/usr/local/go/src/net/http/server.go:1425 +0x947
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7ffa1d5f8740, 0x72, 0xc8207b9000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8207b4450, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8207b4450, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8207b43f0, 0xc8207b9000, 0x1000, 0x1000, 0x0, 0x7ffa2001c050, 0xc82000e018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820116018, 0xc8207b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7ffa20021928, 0xc820116018, 0xc82036e958, 0xc8207b9000, 0x1000, 0x1000, 0xc820b13ec0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc820386ea0, 0xc8207b9000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820126480)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820126480, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82036e8f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc82036e8f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 36 [IO wait]:
net.runtime_pollWait(0x7ffa1d5f8800, 0x72, 0xc8207d9000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8205c4060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205c4060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205c4000, 0xc8207d9000, 0x1000, 0x1000, 0x0, 0x7ffa2001c050, 0xc82000e018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120008, 0xc8207d9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8202c0240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8202c0240, 0xc820e7b788, 0x2, 0x8, 0x23f09c0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).readFull(0xc82015c100, 0xc820e7b788, 0x2, 0x8, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:617 +0xa9
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc82015c100, 0xa, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:641 +0x159
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc82015c100, 0xc820466e98, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:780 +0x80
github.com/weaveworks/scope/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc82015c100, 0x1a1d930, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/websocket/conn.go:852 +0x55
github.com/weaveworks/scope/common/xfer.(*pingingWebsocket).ReadMessage(0xc8203d45c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/common/xfer/websocket.go:108 +0xb2
github.com/weaveworks/scope/app.handleWebsocket.func1(0xc8202c0300, 0x7ffa1d637130, 0xc8203d45c0)
	/go/src/github.com/weaveworks/scope/app/api_topology.go:86 +0x4c
created by github.com/weaveworks/scope/app.handleWebsocket
	/go/src/github.com/weaveworks/scope/app/api_topology.go:94 +0x133

goroutine 63 [chan receive, 33 minutes]:
github.com/weaveworks/scope/app.handleProbeWS.func1(0x7ffa1d5f9238, 0xc8202c92f0, 0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/go/src/github.com/weaveworks/scope/app/controls.go:83 +0x5e3
github.com/weaveworks/scope/app.requestContextDecorator.func1(0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/go/src/github.com/weaveworks/scope/app/router.go:37 +0x226
net/http.HandlerFunc.ServeHTTP(0xc8203db430, 0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/weaveworks/scope/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203dc500, 0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
github.com/weaveworks/scope/app.TopologyHandler.func1(0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/go/src/github.com/weaveworks/scope/app/router.go:113 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc8203d4fa0, 0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820153d00, 0x7ffa1d5f90a8, 0xc82036e750, 0xc82029c620)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820152700)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 38 [select]:
net/http.(*persistConn).writeLoop(0xc820068340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 37 [IO wait]:
net.runtime_pollWait(0x7ffa1d5f85c0, 0x72, 0xc8207aa000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82040c610, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82040c610, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82040c5b0, 0xc8207aa000, 0x1000, 0x1000, 0x0, 0x7ffa2001c050, 0xc82000e018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820116008, 0xc8207aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7ffa1d5f8dc0, 0xc820116008, 0xc8200683a8, 0xc8207aa000, 0x1000, 0x1000, 0x411df3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8203e00c0, 0xc8207aa000, 0x1000, 0x1000, 0xc820031d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820064180)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820064180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820068340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 628 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7ffa1d5f8680, 0x72, 0xc820f3c000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8213b5250, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8213b5250, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8213b51f0, 0xc820f3c000, 0x1000, 0x1000, 0x0, 0x7ffa2001c050, 0xc82000e018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82181d720, 0xc820f3c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.(*connReader).Read(0xc8224c6ae0, 0xc820f3c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:526 +0x196
bufio.(*Reader).fill(0xc821dd6f00)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc821dd6f00, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc821dd6f00, 0x0, 0x0, 0x0, 0x16cf800, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8219c41b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8219c41b0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x40
net/http.readRequest(0xc821dd6f00, 0x100, 0xc820369180, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:721 +0xb6
net/http.(*conn).readRequest(0xc82006a200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:705 +0x359
net/http.(*conn).serve(0xc82006a200)
	/usr/local/go/src/net/http/server.go:1425 +0x947
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1087

### CODE REVIEW

File: render/topologies.go [hunk 1]
```diff
@@ -184,12 +187,12 @@ func (r containerWithImageNameRenderer) Render(rpt report.Report) RenderableNode
...
-		c.Latest = image.Latest.Merge(c.Latest)
-		containers[id] = c
+		output := c.Copy()
+		output.Rank = ImageNameWithoutVersion(image.LabelMajor)
+		output.Latest = image.Latest.Merge(c.Latest)
+		outputs[id] = output
 	}
-
-	return containers
+	return outputs
```
Comment (paulbellamy) [inline render/topologies.go]: also here

**Comment by tomwilkie** [comment]
@paulbellamy PTAL
