### PR TITLE
Ignore conntracked connections on which we never saw an update

### LINKED ISSUE #1462: Edges the wrong way around
See the screenshot:
screen shot 2016-05-10 at 14 19 10

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1462

### CODE REVIEW

**Comment by 2opremio** [comment]
Shouldn't we only be paying attention to ESTABLISHED events?

**Comment by tomwilkie** [comment]
> Shouldn't we only be paying attention to ESTABLISHED events?

Yeah I thought about that, but the way it works it to buffer old flows that came and went during the reporting period.  So those connections would never be ESTABLISHED.

File: probe/endpoint/nat.go [hunk 1]
```diff
@@ -60,6 +60,10 @@ func (n natMapper) applyNAT(rpt report.Report, scope string) {
 		if !ok {
 			return
 		}
+		// Don't apply nat mappings to conntracked connections
+		if _, procspied := node.Latest.Lookup(Procspied); !procspied {
```
Comment (2opremio) [inline probe/endpoint/nat.go]: Why not? If we do this we should move SNATing for short-lived connections to report.go

Comment (tomwilkie) [inline probe/endpoint/nat.go]: Yes this was a old change (I thought this might have been one of the causes of the reversed connections).

We should do source natting in conntrack too, as this isn't going to work for most short lived connections (as this is periodic and only gets current connections).

Comment (2opremio) [inline probe/endpoint/nat.go]: Great, would you mind creating a ticket for it?

**Comment by 2opremio** [comment]
LGTM
