### PR TITLE
Nice and red and blinky ui label for broken plugins

### LINKED ISSUE #1271: Plugins UI should have some indicator when plugins are broken
Raised in: https://github.com/weaveworks/scope/pull/1126#issuecomment-208873500

### PR DESCRIPTION
**Pull request by foot**
Fixes #1271

### CODE REVIEW

File: client/app/scripts/components/plugins.js [hunk 1]
```diff
@@ -1,10 +1,20 @@
 import React from 'react';
+import classNames from 'classnames';
 
 export default class Plugins extends React.Component {
-  renderPlugin(plugin) {
+  renderPlugin({id, label, description, status}) {
+    const error = status !== 'ok';
+    const className = classNames({ error });
+    const title = error ?
+      `Status: ${status}. (Plugin description: ${description})` :
```
Comment (2opremio) [inline client/app/scripts/components/plugins.js]: Maybe we should get the same format regardless of whether there's an error.

Comment (davkal) [inline client/app/scripts/components/plugins.js]: +1, i think it's good seeing that things are ok.

Comment (foot) [inline client/app/scripts/components/plugins.js]: Yes, agree! Good suggestion!

File: client/app/scripts/stores/app-store.js [hunk 2]
```diff
@@ -46,7 +46,7 @@ let highlightedEdgeIds = makeSet();
 let highlightedNodeIds = makeSet();
 let hostname = '...';
 let version = '...';
-let plugins = null;
+let plugins = [];
```
Comment (davkal) [inline client/app/scripts/stores/app-store.js]: Can we use immutables here instead?

Comment (foot) [inline client/app/scripts/stores/app-store.js]: yessss we cannn

File: client/app/styles/main.less [hunk 3]
```diff
@@ -1007,6 +1007,11 @@ h2 {
     content: ', ';
   }
 
+  .error {
+    animation: blinking 2.0s 30 @base-ease; // blink for 1 minute;
+    color: darkred;
```
Comment (davkal) [inline client/app/styles/main.less]: I think that's our first use of red for an error. Do we really need it?

**Comment by davkal** [comment]
The blinking red is a bit subtle, and our first use of red to depict an error. The reconnect error that is displayed when the backend is not available, blinks with a circled exclamation mark. Why not just use that?

**Comment by foot** [comment]
First thought is that is was very icon heavy down there so didn't actually
try it out. Will give it a spin.

**Comment by davkal** [comment]
There is a `fa` icon w/o the circle if that helps.
