### PR TITLE
Do not infer short-lived connections for host-networking containers

### LINKED ISSUE #1598: Wrongly attributed local side in outbound internet connections
I was running the service locally to test the 0.16 release (https://github.com/weaveworks/scope/pull/1587) and got puzzled when I saw authfe was talking to the internet

screen shot 2016-06-17 at 13 26 09

Then I realized that it's due to the new logging sidecar talking to bigquery: 

```
vagrant@vagrant-ubuntu-wily-64:~/scope$ docker ps | grep logging
991a8908520e        quay.io/weaveworks/logging                                         "/bin/sh -c 'exec flu"   20 minutes ago      Up 20 minutes                                   k8s_logging.6359526a_authfe-4cptq_default_b6d0e6fd-3478-11e6-a11f-0242ac110004_84cf3379
vagrant@vagrant-ubuntu-wily-64:~/scope$ docker exec -ti k8s_logging.6359526a_authfe-4cptq_default_b6d0e6fd-3478-11e6-a11f-0242ac110004_84cf3379 sh
/home/fluent # netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 authfe-4cptq:47110      lhr25s02-in-f106.1e100.net:https TIME_WAIT   
tcp        0      0 authfe-4cptq:51680      lhr25s07-in-f10.1e100.net:https TIME_WAIT   
tcp        0      0 authfe-4cptq:54850      lhr26s02-in-f10.1e100.net:https TIME_WAIT   
tcp        0      0 authfe-4cptq:47208      lhr25s02-in-f106.1e100.net:https TIME_WAIT   
tcp        0      0 authfe-4cptq:57374      lhr25s09-in-f10.1e100.net:https ESTABLISHED 
tcp        0      0 authfe-4cptq:54098      lhr26s02-in-f10.1e100.net:https TIME_WAIT   
tcp        0      0 authfe-4cptq:47396      lhr25s02-in-f10.1e100.net:https ESTABLISHED 
tcp        0      0 authfe-4cptq:53096      lhr26s03-in-f10.1e100.net:https TIME_WAIT   
tcp        0      0 authfe-4cptq:55212      lhr26s02-in-f10.1e100.net:https ESTABLISHED 
tcp        0      0 authfe-4cptq:51948      10.27.204.4:http        ESTABLISHED 
tcp        0      0 localhost:54352         localhost:24224         ESTABLISHED 
tcp        0      0 authfe-4cptq:47370      lhr25s02-in-f10.1e100.net:https TIME_WAIT   
...
```

... but the local side is being attributed to a scope probe instead of the authfe pod (note the the connections to hosts like `lhr25s01-in-f74.1e100.net` from `scope-probe-tgeqv`)

Report: [report.json.gz](https://github.com/weaveworks/scope/files/320317/report.json.gz)

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #1598

### CODE REVIEW

File: probe/docker/reporter.go [hunk 1]
```diff
@@ -191,30 +192,35 @@ func (r *Reporter) containerTopology(localAddrs []net.IP) report.Topology {
 				Add(ContainerIPsWithScopes, report.MakeStringSet(hostIPsWithScopes...))
 		}
 
-		var networkInfo func(prefix string) report.Sets
-		networkInfo = func(prefix string) report.Sets {
+		var networkInfo func(prefix string) (report.Sets, bool)
+		networkInfo = func(prefix string) (ips report.Sets, isHostMapped bool) {
```
Comment (tomwilkie) [inline probe/docker/reporter.go]: I'm not normally a stickler for names, but can we call this something else?  like `inHostNamespace`?

Also pls put a comment about how we can't use the networkmode to detect this, due to `--net=container:foo`

File: render/container.go [hunk 2]
```diff
@@ -249,7 +249,11 @@ var portMappingMatch = regexp.MustCompile(`([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.
 func MapContainer2IP(m report.Node) []string {
 	// if this container doesn't make connections, we can ignore it
 	_, doesntMakeConnections := m.Latest.Lookup(report.DoesNotMakeConnections)
-	if doesntMakeConnections {
+	// if this container belongs to the host's networking namespace
+	// we cannot use its IP to attribute connections
+	// (they could come from any other process on the host or DNAT-ed IPs)
+	_, isInHostNetwork := m.Latest.Lookup(docker.IsInHostNetwork)
+	if doesntMakeConnections || isInHostNetwork {
```
Comment (tomwilkie) [inline render/container.go]: I was going to say "Instead of adding a new key, can we rename `DoesNotMakeConnections`" but it occurs to me that will not be backwards compatible.

How bad would it be to just reuse `DoesNotMakeConnections`?

**Comment by tomwilkie** [comment]
2 minor nits but otherwise LGTM

File: render/container.go (hunk 2 above)
Comment (2opremio) [inline render/container.go]: I thought about that, but the name is a bit too misleading.

Comment (tomwilkie) [inline render/container.go]: Okay, nevermind! 👍
