### PR TITLE
Apply format to tooltips in sparkline hovers

### LINKED ISSUE #1224: metric number formatting is not applied in tooltips
To reproduce:
1) Go to the hosts view
2) Open the detail panel on a host
3) Check the tooltip over the Memory sparkline

Expected behaviour: numbers are displayed in megabytes
Actual behaviour: numbers are displayed in bytes

### PR DESCRIPTION
**Pull request by davkal**
Fixes #1224

### CODE REVIEW

File: client/app/scripts/components/node-details/node-details-health-item.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ function NodeDetailsHealthItem(props) {
     <div className="node-details-health-item">
     <div className="node-details-health-item-value">{formatMetric(props.value, props)}</div>
       <div className="node-details-health-item-sparkline">
-        <Sparkline data={props.samples} max={props.max}
+        <Sparkline data={props.samples} max={props.max} format={props.format}
```
Comment (foot) [inline client/app/scripts/components/node-details/node-details-health-item.js]: Not sure if this gets used anywhere?

**Comment by foot** [comment]
Slick! LGTM

File: client/app/scripts/components/node-details/node-details-health-item.js (hunk 1 above)
Comment (davkal) [inline client/app/scripts/components/node-details/node-details-health-item.js]: Yes, `formatMetrics` one component down. Maybe it's not that transparent.
