### PR TITLE
Don't assume pseudo nodes have edges _away_ from them

### LINKED ISSUE #422: panic: index out of range
```
http: panic serving 212.121.131.210:61894: runtime error: index out of range
 . . .
/home/peter/src/github.com/weaveworks/scope/render/mapping.go:173 +0x53d
```

[relevant line](https://github.com/weaveworks/scope/blob/e867d168e171e6b746119552476eb1ff54ad1bd3/render/mapping.go#L173).

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #422

### CODE REVIEW

File: render/mapping.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ func MapEndpointIdentity(m report.NodeMetadata, local report.Networks) Renderabl
 
 		// We are a 'client' pseudo node if the port is in the ephemeral port range.
 		// Linux uses 32768 to 61000.
-		if p, err := strconv.Atoi(port); err == nil && p >= 32768 && p < 61000 {
+		if p, err := strconv.Atoi(port); err == nil && len(m.Adjacency) > 0 && p >= 32768 && p < 61000 {
```
Comment (peterbourgon) [inline render/mapping.go]: Ah, yes :)

**Comment by peterbourgon** [comment]
:+1: pending Circle.
