### PR TITLE
silence abnormal websocket close

### LINKED ISSUE #1202: Socket/websocket errors
Coming from user jcw in scope-public. They may be harmless but a bit alarming nonetheless.

```
<app> INFO: 2016/03/23 08:11:21.645969 app starting, version 88cd85f, ID 246bdd25a0c27482
<app> INFO: 2016/03/23 08:11:21.646557 listening on :4040
<app> ERRO: 2016/03/23 08:11:24.836361 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:24.849318 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:31.901864 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:31.904767 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:31.953049 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:31.954445 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:32.008110 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:32.041632 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:32.122026 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> ERRO: 2016/03/23 08:11:32.124800 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> INFO: 2016/03/23 08:21:11.966655 Creating pipe id pipe-9128703718824575860
<app> INFO: 2016/03/23 08:21:11.966771 Success got pipe pipe-9128703718824575860:probe
<app> INFO: 2016/03/23 08:21:12.164727 Success got pipe pipe-9128703718824575860:ui
<app> INFO: 2016/03/23 08:21:22.372794 Creating pipe id pipe-2460789589887443699
<app> INFO: 2016/03/23 08:21:22.372958 Success got pipe pipe-2460789589887443699:probe
<app> INFO: 2016/03/23 08:21:22.571248 Success got pipe pipe-2460789589887443699:ui
<app> INFO: 2016/03/23 08:22:21.646652 Timing out pipe pipe-9128703718824575860
<app> ERRO: 2016/03/23 08:22:22.712037 Error getting pipe pipe-9128703718824575860: Pipe pipe-9128703718824575860 closed
<app> INFO: 2016/03/23 08:26:16.712829 Success got pipe pipe-2460789589887443699:probe
<app> INFO: 2016/03/23 08:26:51.663656 Timing out pipe pipe-2460789589887443699
<app> ERRO: 2016/03/23 08:26:53.667303 Error getting pipe pipe-2460789589887443699: Pipe pipe-2460789589887443699 closed
<app> ERRO: 2016/03/23 08:31:17.155764 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:33422: i/o timeout
<app> INFO: 2016/03/23 08:31:17.157527 err: read tcp 10.1.42.7:4040->10.1.42.1:33422: use of closed network connection
<app> ERRO: 2016/03/23 08:36:04.193213 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:45304: i/o timeout
<app> INFO: 2016/03/23 08:36:04.193325 err: read tcp 10.1.42.7:4040->10.1.42.1:45304: use of closed network connection
<app> INFO: 2016/03/23 08:41:11.114890 err: read tcp 10.1.42.7:4040->10.1.42.1:48836: i/o timeout
<app> ERRO: 2016/03/23 08:41:11.937388 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:48836: i/o timeout
<app> ERRO: 2016/03/23 08:46:09.404700 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:52434: i/o timeout
<app> INFO: 2016/03/23 08:46:09.405784 err: read tcp 10.1.42.7:4040->10.1.42.1:52434: use of closed network connection
<app> ERRO: 2016/03/23 08:51:07.981397 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:56324: i/o timeout
<app> INFO: 2016/03/23 08:51:07.981763 err: read tcp 10.1.42.7:4040->10.1.42.1:56324: use of closed network connection
<app> ERRO: 2016/03/23 08:56:05.330197 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:60082: i/o timeout
<app> INFO: 2016/03/23 08:56:05.330309 err: read tcp 10.1.42.7:4040->10.1.42.1:60082: use of closed network connection
<app> ERRO: 2016/03/23 12:40:57.066641 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:33964: i/o timeout
<app> ERRO: 2016/03/23 12:40:57.066712 websocket ping error: write tcp 10.1.42.7:4040->10.1.42.1:33964: use of closed network connection
<app> INFO: 2016/03/23 12:40:57.066739 err: read tcp 10.1.42.7:4040->10.1.42.1:33964: use of closed network connection
<app> ERRO: 2016/03/23 12:45:51.046418 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:60520: i/o timeout
<app> INFO: 2016/03/23 12:45:51.046513 err: read tcp 10.1.42.7:4040->10.1.42.1:60520: use of closed network connection
<app> ERRO: 2016/03/23 13:01:03.518084 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:43064: i/o timeout
<app> INFO: 2016/03/23 13:01:03.520240 err: read tcp 10.1.42.7:4040->10.1.42.1:43064: use of closed network connection
<app> ERRO: 2016/03/23 13:05:47.174285 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:46680: i/o timeout
<app> INFO: 2016/03/23 13:05:47.174477 err: read tcp 10.1.42.7:4040->10.1.42.1:46680: use of closed network connection
<app> ERRO: 2016/03/23 13:14:56.709672 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:50786: i/o timeout
<app> INFO: 2016/03/23 13:14:56.709743 err: read tcp 10.1.42.7:4040->10.1.42.1:50786: use of closed network connection
<app> ERRO: 2016/03/23 13:19:50.392420 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:56504: i/o timeout
<app> ERRO: 2016/03/23 13:19:50.392531 websocket ping error: write tcp 10.1.42.7:4040->10.1.42.1:56504: use of closed network connection
<app> INFO: 2016/03/23 13:19:50.392604 err: read tcp 10.1.42.7:4040->10.1.42.1:56504: use of closed network connection
<app> INFO: 2016/03/23 13:24:51.226396 err: read tcp 10.1.42.7:4040->10.1.42.1:59762: use of closed network connection
<app> ERRO: 2016/03/23 13:24:51.226613 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:59762: i/o timeout
<app> ERRO: 2016/03/23 13:29:57.887893 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:34982: i/o timeout
<app> ERRO: 2016/03/23 13:29:57.888015 websocket ping error: write tcp 10.1.42.7:4040->10.1.42.1:34982: use of closed network connection
<app> INFO: 2016/03/23 13:29:57.888054 err: read tcp 10.1.42.7:4040->10.1.42.1:34982: use of closed network connection
<app> ERRO: 2016/03/23 13:34:49.984684 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:38588: i/o timeout
<app> INFO: 2016/03/23 13:34:49.984889 err: read tcp 10.1.42.7:4040->10.1.42.1:38588: use of closed network connection
<app> ERRO: 2016/03/23 13:39:53.332824 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:42312: i/o timeout
<app> INFO: 2016/03/23 13:39:53.333021 err: read tcp 10.1.42.7:4040->10.1.42.1:42312: use of closed network connection
<app> ERRO: 2016/03/23 13:48:58.785148 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:46410: i/o timeout
<app> INFO: 2016/03/23 13:48:58.785313 err: read tcp 10.1.42.7:4040->10.1.42.1:46410: use of closed network connection
<app> ERRO: 2016/03/23 13:58:51.442940 cannot serialize topology diff: write tcp 10.1.42.7:4040->10.1.42.1:55674: i/o timeout
<app> INFO: 2016/03/23 13:58:51.443039 err: read tcp 10.1.42.7:4040->10.1.42.1:55674: use of closed network connection
```

### PR DESCRIPTION
**Pull request by rade**
- silence `websocket.CloseAbnormalClose` since we get this when attach/exec windows are closed
- reduce pipe log noise
- improve some of the remaining pipe logging

Fixes #1202.

### CODE REVIEW

File: probe/appclient/app_client.go [hunk 1]
```diff
@@ -311,7 +311,10 @@ func (c *appClient) pipeConnection(id string, pipe xfer.Pipe) (bool, error) {
 	defer c.closeConn(id)
 
 	_, remote := pipe.Ends()
-	return false, pipe.CopyToWebsocket(remote, conn)
+	if err := pipe.CopyToWebsocket(remote, conn); err != nil && !xfer.IsExpectedWSCloseError(err) {
+		return false, err
+	}
+	return false, nil
```
Comment (rade) [inline probe/appclient/app_client.go]: This is a change in behaviour. Previously any error at this stage would be handled by the backoff logic. Now only unexpected errors cause backoff (and are logged); expected errors cause an immediate retry.

@paulbellamy @fons is this bad?

We could return `true, nil` instead, which would cause the backoff loop to be aborted. Would that be better? What conditions is the backoff supposed to handle?

Comment (2opremio) [inline probe/appclient/app_client.go]: > @paulbellamy @fons is this bad?

I think it would be fine, but @tomwilkie can give a better answer here.

**Comment by 2opremio** [comment]
LGTM

**Comment by davkal** [comment]
Is this purely about logging, or did some signalling change too?

**Comment by rade** [comment]
> did some signalling change too?

Not intentionally.

File: probe/appclient/app_client.go (hunk 1 above)
Comment (tomwilkie) [inline probe/appclient/app_client.go]: TBH not sure, its been a long time since I worked on this.  There is a separate mechanism to decide when to stop retrying (the 404 above).  Originally it was supposed to retry / backoff until this is hit.

Comment (2opremio) [inline probe/appclient/app_client.go]: I still think it's fine to merge it like this. @rade , your call.
