### PR TITLE
Fix processes/hosts table not appearing

### LINKED ISSUE #2822: Table mode: unable to see processes
It was working before, then I refreshed the window and I just get a blank page:

image

Switching to topology view I see lots of processes.

URL is https://cloud.weave.works/app/loud-breeze-77#!/state/{"controlPipe":null,"nodeDetails":[],"topologyViewMode":"grid","pinnedSearches":[],"searchQuery":"","gridSortedBy":"docker_cpu_total_usage","gridSortedDesc":true,"topologyId":"processes","topologyOptions":{"processes":{"unconnected":["hide"]},"containers":{"system":["application"],"stopped":["running"],"pseudo":["hide"],"namespace":[""]},"pods":{"pseudo":["hide"],"namespace":[""]}},"contrastMode":false}

### PR DESCRIPTION
**Pull request by rndstr**
Closes #2822

### CODE REVIEW

File: client/app/scripts/components/cloud-link.js [hunk 1]
```diff
@@ -57,7 +57,7 @@ class LinkWrapper extends React.Component {
   render() {
     const { url, children, ...props } = this.props;
     if (!url) {
-      return children;
+      return React.isValidElement(children) ? children : (<span>{children}</span>);
```
Comment (jpellizzari) [inline client/app/scripts/components/cloud-link.js]: Under what circumstances would this not be valid? This still wraps an invalid element in span tags.

Comment (rndstr) [inline client/app/scripts/components/cloud-link.js]: That would be a number and by being wrapped it becomes valid.

Comment (jpellizzari) [inline client/app/scripts/components/cloud-link.js]: 👍
