### PR TITLE
Obtain local pods from kubelet

### LINKED ISSUE #2049: kubernetes reporter is broken on katacoda
You can reproduce it here: https://www.weave.works/guides/cloud-testdrive-part-1-setup-troubleshooting/.

The symptoms:
- now kubernetes view in the app
- probes log `error generating report: open /sys/hypervisor/uuid: no such file or directory`

Details:

Katacoda doesn't have `/sys/class/dmi/id/product_uuid`, and we incorrectly fallback to `/sys/hypervisor/uuid`, which is also missing.

The code is in [`probe/kubernetes/reporter.go#L319`](https://github.com/weaveworks/scope/blob/92a02fb587624222ed85ee5d480c0eb7d1842ca5/probe/kubernetes/reporter.go#L319) and it looks very much identical to what we have in [`vendor/github.com/weaveworks/go-checkpoint/checkpoint.go#L342`](https://github.com/weaveworks/scope/blob/92a02fb587624222ed85ee5d480c0eb7d1842ca5/vendor/github.com/weaveworks/go-checkpoint/checkpoint.go#L342), except that [we ingnore the error](https://github.com/weaveworks/scope/blob/92a02fb587624222ed85ee5d480c0eb7d1842ca5/vendor/github.com/weaveworks/go-checkpoint/checkpoint.go#L144) in the checkpointing code.

What this code is trying to do is find _this node_ in Kubernetes API, which is something I've looked into from `kubeadm` perspective, and it's not as simple as you'd wish...

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #2049

Supersedes #2122 

@paulbellamy PTAL

### CODE REVIEW

File: probe/kubernetes/kubelet_test.go [hunk 1]
```diff
@@ -0,0 +1,73 @@
+package kubernetes_test
```
Comment (rade) [inline probe/kubernetes/kubelet_test.go]: Why are we putting tests in a different package to the code being tested, and hence have to export functions that otherwise would be local? I don't think that's The Go Way.

Comment (2opremio) [inline probe/kubernetes/kubelet_test.go]: To be honest, I don't know why and when we started doing this. @paulbellamy any idea?

Comment (2opremio) [inline probe/kubernetes/kubelet_test.go]: Here's why https://github.com/weaveworks/scope/commit/2b7662a3c6a7cb1b77908e9d169b3f44c651e4d3#commitcomment-20502161

Comment (2opremio) [inline probe/kubernetes/kubelet_test.go]: I will make the symbols private after merging https://github.com/weaveworks/scope/pull/2136 (which contains https://github.com/weaveworks/build-tools/pull/64 )

Comment (2opremio) [inline probe/kubernetes/kubelet_test.go]: I was hoping I would do this here, but making those symbols private imply making `reporter_rest.go` not import the kubernetes package, which implies a rather large refactoring.
