### PR TITLE
fix(probe): Use a buffered chan to reduce the chance of losing events

### LINKED ISSUE #3576: Report sizes seem to increase over days after a restart
Noticed in data from a lot of probes - this is the average report size over the last 30 days:

image

The two drops are at points where all probes were restarted.
Pattern seems to suggest the probes are accumulating stuff in data structures which does not come back on restart, and therefore probably unnecessary.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #3576 (I know, we've been here before...)

Event notifications from Docker have been seen to get dropped; using a buffered chan seems to reduce the chance of this happening.

### CODE REVIEW

File: probe/docker/registry.go [hunk 1]
```diff
@@ -176,7 +176,8 @@ func (r *registry) listenForEvents() bool {
 	// Next, start listening for events.  We do this before fetching
 	// the list of containers so we don't miss containers created
 	// after listing but before listening for events.
-	events := make(chan *docker_client.APIEvents)
+	// Use a buffered chan to reduce the chance of losing events
+	events := make(chan *docker_client.APIEvents, 32)
```
Comment (rade) [inline probe/docker/registry.go]: Where do the events get dropped? Is the sender using a non-blocking send?

Comment (bboreham) [reply probe/docker/registry.go]: Unclear. Not in `fsouza/go-dockerclient`.
Maybe the other side of the socket.

Comment (bboreham) [reply probe/docker/registry.go]: Here you go: https://github.com/moby/moby/blob/a6e1502575858cd063b0e75d400e04b6f334e86d/daemon/events/events.go#L114

Comment (bboreham) [reply probe/docker/registry.go]: Also `// Each listener has 100 milliseconds to receive the event or it will be skipped.`

Comment (rade) [reply probe/docker/registry.go]: Is there any downside to making the buffer a lot larger (but not as large as to become a memory hog)?

Comment (bboreham) [reply probe/docker/registry.go]: Like 1024?  I don't see any issue.
Really we need to do a full sync periodically, so I see this change as an improvement but not a final fix.

Comment (rade) [reply probe/docker/registry.go]: 1024 sounds reasonable.

Pls file an issue for the periodic sync.

Comment (bboreham) [reply probe/docker/registry.go]: Filed https://github.com/weaveworks/scope/issues/3629
