### PR TITLE
Fixes the terminal spamming POST requests on resize

### LINKED ISSUE #1974: TTY resizing goes nuts when detaching terminal window
Tested on http://frontend.dev.weave.works/app/nameless-night-79

You can see a video showing the problem at http://recordit.co/BGPayC8clP

### PR DESCRIPTION
**Pull request by foot**
Forgot to debounce the initial implementation

Fixes #1974

### CODE REVIEW

File: client/app/scripts/components/terminal.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ import React from 'react';
 import ReactDOM from 'react-dom';
 import { connect } from 'react-redux';
 import classNames from 'classnames';
+import _ from 'lodash';
```
Comment (davkal) [inline client/app/scripts/components/terminal.js]: we should start using partial imports.

**Comment by davkal** [comment]
LGTM
