### PR TITLE
Fix node scoping rules

### LINKED ISSUE #227: Cross-host connects not showing in UI when connection traverses docker port mapping
conn

### PR DESCRIPTION
**Pull request by peterbourgon**
We only want to scope (i.e. prefix with hostID) those addresses that are deemed loopback, to disambiguate them. Otherwise, we want to leave addresses in unscoped form, so they can be matched, and links between communicating nodes properly made.

So, we make the isLoopback check in MakeAddressID, and omit hostID if the address isn't loopback. So far so good.

But this breaks topology rendering, as we were relying on extracting hostID from adjacency node IDs, to populate origin hosts in the rendered node output. So we need another way to get origin host from an arbitrary node.

A survey revealed no reliable way to get that information from IDs in their new form. However, we have access to node metadata, so this changeset introduces the OriginHostTagger, which tags each node with its origin host, via the foreign-key semantics we'll use going forward.

Fixes #227

### CODE REVIEW

File: probe/tag/origin_host_tagger.go [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+type originHostTagger struct{ hostNodeID string }
+
+// NewOriginHostTagger tags each node with a foreign key linking it to its
+// origin host in the host topology.
+func NewOriginHostTagger(hostID string) Tagger {
+	return &originHostTagger{hostNodeID: report.MakeHostNodeID(hostID)}
+}
+
+func (t originHostTagger) Tag(r report.Report) report.Report {
```
Comment (tomwilkie) [inline probe/tag/origin_host_tagger.go]: Could slightly adapt and use report.Topologies here?

File: probe/tag/topology_tagger.go [hunk 2]
```diff
@@ -13,8 +13,11 @@ func NewTopologyTagger() Tagger {
 
 func (topologyTagger) Tag(r report.Report) report.Report {
 	for val, topology := range map[string]*report.Topology{
```
Comment (tomwilkie) [inline probe/tag/topology_tagger.go]: Similarly here.

**Comment by tomwilkie** [comment]
Otherwise LGTM
