### PR TITLE
fix: report http error if /api call fails

### LINKED ISSUE #3249: Error fetching app details: only encoded map or array can be decoded into a struct
Running scope v1.9.0 with Kubernetes v1.7. Error logs are not very useful, below:

```
time="2018-07-02T21:07:56Z" level=info msg="publishing to: weave.jws:443" 
<probe> INFO: 2018/07/02 21:07:56.991032 command line args: --mode=probe --probe-only=true --probe.docker=true --probe.docker.bridge=docker0 --probe.insecure=true --probe.kubernetes=true --weave=false weave.jws:443
<probe> INFO: 2018/07/02 21:07:56.991297 probe starting, version 1.9.0, ID 8d069c657b78c3a
<probe> ERRO: 2018/07/02 21:07:57.116622 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:07:57.118318 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> INFO: 2018/07/02 21:07:57.614628 kubernetes: targeting api server https://10.0.0.1:443
<probe> ERRO: 2018/07/02 21:07:57.684642 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.
<probe> ERRO: 2018/07/02 21:07:58.451025 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:07:58.471302 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:00.384524 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:00.384728 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:04.243500 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:04.247383 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:12.236634 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:12.237983 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:22.342833 Error fetching app details: only encoded map or array can be decoded into a struct
<probe> ERRO: 2018/07/02 21:08:22.347560 Error fetching app details: only encoded map or array can be decoded into a struct
```

### PR DESCRIPTION
**Pull request by bboreham**
Previously it would try to run the JSON decoder on a string like "404 not found" and report that failing with the message "Error fetching app details: only encoded map or array can be decoded into a struct".

Now it will report the http error, like this:
```
<probe> ERRO: 2019/10/06 17:00:42.290708 Error fetching app details: Error response from http://172.16.0.3:4040//api: 404 Not Found
```

Fixes #3249

### CODE REVIEW

File: probe/appclient/app_client.go [hunk 1]
```diff
@@ -192,6 +192,9 @@ func (c *appClient) Details() (xfer.Details, error) {
 	if err != nil {
 		return result, err
 	}
+	if resp.StatusCode != http.StatusOK {
+		return result, fmt.Errorf("Error response from %s: %s", c.url("/api"), resp.Status)
```
Comment (fbarl) [inline probe/appclient/app_client.go]: Nit: based on your own log output (`Error response from http://172.16.0.3:4040//api: 404 Not Found`), maybe there's an extra `/` here:

```suggestion
		return result, fmt.Errorf("Error response from %s: %s", c.url("api"), resp.Status)
```

Comment (bboreham) [reply probe/appclient/app_client.go]: The output is correct: the reason it's failing is the url has too many slashes in it.

**Comment by bboreham** [comment]
#3249 has (like many of our issues) multiple people reporting multiple sets of symptoms.
As far as I can see most of the people commenting subsequently realised it was an addressing problem, which this change will help them with.
People who still have problems can open a new issue.
