### PR TITLE
Use poll in TestRegistryEvents.

### LINKED ISSUE #311: TestRegistryEvents is flaky
```
2015/07/08 11:32:42 docker container: collecting stats for ping
2015/07/08 11:32:42 docker container: error reading event io: read/write on closed pipe
2015/07/08 11:32:42 docker container: stopped collecting stats for ping
--- FAIL: TestRegistryEvents-4 (0.00s)
	registry_test.go:196: 
		--- want
		+++ have
		@@ -1,53 +1,3 @@
		-([]docker.Container) (len=2 cap=2) {
		- (*docker_test.mockContainer)(0xc2080ee018)({
		-  c: (*docker.Container)(0x14b4440)({
		-   ID: (string) (len=4) "ping",
		-   Created: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
		-   Path: (string) "",
		-   Args: ([]string) <nil>,
		-   Config: (*docker.Config)(<nil>),
		-   State: (docker.State) Up 2562047h47m16.854775807s,
		-   Image: (string) (len=3) "baz",
		-   Node: (*docker.SwarmNode)(<nil>),
		-   NetworkSettings: (*docker.NetworkSettings)(<nil>),
		-   SysInitPath: (string) "",
		-   ResolvConfPath: (string) "",
		-   HostnamePath: (string) "",
		-   HostsPath: (string) "",
		-   Name: (string) (len=4) "pong",
		-   Driver: (string) "",
		-   Volumes: (map[string]string) <nil>,
		-   VolumesRW: (map[string]bool) <nil>,
		-   HostConfig: (*docker.HostConfig)(<nil>),
		-   ExecIDs: ([]string) <nil>,
		-   RestartCount: (int) 0,
		-   AppArmorProfile: (string) ""
		-  })
		- }),
		- (*docker_test.mockContainer)(0xc2080ee020)({
		-  c: (*docker.Container)(0x14b45c0)({
		-   ID: (string) (len=4) "wiff",
		-   Created: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
		-   Path: (string) "",
		-   Args: ([]string) <nil>,
		-   Config: (*docker.Config)(<nil>),
		-   State: (docker.State) Up 2562047h47m16.854775807s,
		-   Image: (string) (len=3) "baz",
		-   Node: (*docker.SwarmNode)(<nil>),
		-   NetworkSettings: (*docker.NetworkSettings)(<nil>),
		-   SysInitPath: (string) "",
		-   ResolvConfPath: (string) "",
		-   HostnamePath: (string) "",
		-   HostsPath: (string) "",
		-   Name: (string) (len=4) "waff",
		-   Driver: (string) "",
		-   Volumes: (map[string]string) <nil>,
		-   VolumesRW: (map[string]bool) <nil>,
		-   HostConfig: (*docker.HostConfig)(<nil>),
		-   ExecIDs: ([]string) <nil>,
		-   RestartCount: (int) 0,
		-   AppArmorProfile: (string) ""
		-  })
		- })
		+([]docker.Container) {
		 }
		 
FAIL
```

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #311

### CODE REVIEW

**Comment by tomwilkie** [comment]
The failure is in the dockerhub, not this code.

**Comment by tomwilkie** [comment]
Ohh new failure

**Comment by tomwilkie** [comment]
\o/ three fixes in one.

File: probe/docker/registry_test.go [hunk 1]
```diff
@@ -183,6 +187,13 @@ func TestRegistryEvents(t *testing.T) {
 		defer registry.Stop()
 		runtime.Gosched()
 
+		check := func(want []docker.Container) {
+			test.Poll(t, 10*time.Millisecond, func() bool {
+				have := allContainers(registry)
+				return reflect.DeepEqual(want, have)
+			}, "Missed event")
```
Comment (2opremio) [inline probe/docker/registry_test.go]: We are missing `test.Diff(want, have)` , but I understand that it may not be possible in golang given how Poll is built.

Comment (tomwilkie) [inline probe/docker/registry_test.go]: Yes.  We could change poll to take a function that returns a interface, and then add the test.Diff code. 

In fact, I'll do that.

**Comment by tomwilkie** [comment]
@2opremio PTAL

**Comment by 2opremio** [comment]
LGTM
