### PR TITLE
Fix edge directionality in graph layout

### LINKED ISSUE #2267: graph not rendered top-down, despite lack of cycles
Here's what Weave Cloud Dev shows for the 'cortex' service:

screenshot_2017-02-22_09-29-43

The distributor and ingester are both rendered below consul, even though they connect *to* consul.

There are no cycles in the directed graph except for the consuls and memcaches connecting to themselves, so there is no intrinsic reason why this couldn't be laid out top-down:

1. querier, ruler, distributor
2. ingester
3. consul, memcached, dynamo, s3
4. The Internet

### PR DESCRIPTION
**Pull request by fbarl**
Fixes #2267.

layout-fixed

The problem was that we were not making a difference between *source* and *target* nodes when constructing edges for the layout engine (for the purpose of not rendering the same edge twice).

~~**Note:** The bidirectional edges are now represented as two directed edges, both in the layout engine and when rendering. So they are actually rendered as two overlapping edges, although that's currently not visible. I intentionally left it like that so that we could make them non-overlapping if we want or have an easier time drawing the arrows later on.~~

### CODE REVIEW

**Comment by rade** [comment]
> The bidirectional edges are now represented as two directed edges, both in the layout engine and when rendering. So they are actually rendered as two overlapping edges, although that's currently not visible. I intentionally left it like that so that we could make them non-overlapping if we want or have an easier time drawing the arrows later on.

Hmm. Not sure about that. I would expect bidirectional edges to be rendered as one edge with two arrowheads.

If it's relatively easy to have one edge for bidirectional edges, let's do that. If not, then what you have is ok.

**Comment by rade** [comment]
btw, was this always broken, or is it a regression?

**Comment by fbarl** [comment]
@rade Alright, I modified the code so that it doesn't render both edges, but I'm still sending them both to the layout engine so that the rank assignment would be more accurate. I cleaned up that code and added some comments and unit tests.

I think I broke edge directions in one of my optimizations stories, so I don't think it was there for too long. However, I think we were always ignoring one direction in case of bidirectional edges, which is something this story also fixes. There is a chance this fix will improve stability and accuracy of some rendered graphs slightly.

**Comment by rade** [comment]
> I think I broke edge directions in one of my optimizations stories,

Did that breakage make it 1.2? If so, we *may* want to release a 1.2.1 with a fix. cc @2opremio

File: client/app/scripts/utils/__tests__/layouter-utils-test.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
+import { fromJS } from 'immutable';
+
+describe('LayouterUtils', () => {
+  const LayouterUtils = require('../layouter-utils');
```
Comment (jpellizzari) [inline client/app/scripts/utils/__tests__/layouter-utils-test.js]: `import` syntax would keep this more consistent

**Comment by fbarl** [comment]
@rade Fortunately the breakage didn't make it into any of the releases as it was introduced on *master* only 2 days ago when merging #2221 (line 19 in [nodes-chart-layout.js](https://github.com/weaveworks/scope/pull/2221/files#diff-bb937cf1c7e428785c32dca6802273bc)).

File: client/app/scripts/utils/__tests__/layouter-utils-test.js (hunk 1 above)
Comment (fbarl) [inline client/app/scripts/utils/__tests__/layouter-utils-test.js]: Agree

**Comment by jpellizzari** [comment]
LGTM. Nice to have tests for this!
